# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dab2f2e7aa2b4d58c460497b419c974d"
name = "test-new-app"
application_url = "https://bhavik.dynamicdreamz.com/shopify/main"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_gift_cards,read_gift_cards,write_orders,read_orders,write_products,read_products"

use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://bhavik.dynamicdreamz.com/auth/callback",
  "https://bhavik.dynamicdreamz.com/auth/shopify/callback",
  "https://bhavik.dynamicdreamz.com/api/auth/callback",
  "https://bhavik.dynamicdreamz.com/api/shopify/auth/callback",
  "https://bhavik.dynamicdreamz.com/shopify/main",
  "https://bhavik.dynamicdreamz.com/shopify"
]

[pos]
embedded = false
