# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c9f2dae08ce0d37db022b21b202c7e9d"
name = "test-new-app"
application_url = "https://9d7371282e2d.ngrok-free.app/shopify/main"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_gift_cards,read_orders,read_products,write_gift_cards,write_orders,write_products"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://9d7371282e2d.ngrok-free.app/auth/callback",
  "https://9d7371282e2d.ngrok-free.app/auth/shopify/callback",
  "https://9d7371282e2d.ngrok-free.app/api/auth/callback",
  "https://9d7371282e2d.ngrok-free.app/api/shopify/auth/callback",
  "https://9d7371282e2d.ngrok-free.app/shopify/main",
  "https://9d7371282e2d.ngrok-free.app/shopify"
]

[pos]
embedded = false
