 # Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dab2f2e7aa2b4d58c460497b419c974d"
name = "test-new-app"
application_url = " https://86fcde31cba5.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
use_legacy_install_flow = false

[auth]
redirect_urls = [
  " https://86fcde31cba5.ngrok-free.app/auth/callback",
  " https://86fcde31cba5.ngrok-free.app/auth/shopify/callback",
  " https://86fcde31cba5.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false